name: AppidQuick

on:
    workflow_dispatch:
        inputs:
            download_url:
                description: 'URL to download the file'
                required: true
                default: 'https://dldir1.qq.com/qqfile/qq/QQNT/0256c948/linuxqq_3.2.12-28418_amd64.deb'
            group_id:
                description: '发送端'
                required: true
                default: '填我填我'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Clone Repository
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 

        - name: 调试环境变量
          run: |
            echo "检查 API 和 SEND_KEY 是否可用："
            echo "API: ${API}"
            echo "SEND_KEY: ${SEND_KEY}"
          env:
            API: ${{ secrets.API }}
            SEND_KEY: ${{ secrets.SEND_KEY }}


        - name: Get Appid
          env:
            API: ${{ secrets.API }}
            SEND_KEY: ${{ secrets.SEND_KEY }}
          run: sudo bash ./GetAppid.sh ${{ github.event.inputs.download_url }} ${{ github.event.inputs.group_id }}